baseURL = "https://agsdot.github.io/test_static_site_hugo/"
languageCode = "en-us"
title = "My Static Site Hugo Blog created purely on github.com online"

# Specify theme as a module
#[module]
#  [[module.imports]]
#    path = "github.com/HugoBlox/theme-academic-cv"
